### ISSUE TITLE
Prevent merges without review approvals on `cli`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#18]
- [x] Add [mergeable](https://probot.github.io/apps/mergeable/) Probot app to `npm` org
- [x] Define a `.github/mergable.yml` file based on [these config options](https://github.com/mergeability/mergeable#configuration)

**Comment by mikemimik** [comment]
Adding a GitHub App for this is a bit overkill unless there is some specific functionality that you don't get from `.github/settings.yml`.

https://github.com/npm/.github/blob/master/.github/settings.yml#L27
This is an example of how you can accomplish this with just the settings file, rather than installing a 3rd party app at the org level.

**Comment by claudiahdz** [comment]
I was unaware this is something we could quickly configure using github settings. Thanks for the pointer @mikemimik! I closed the previous PR and opened a new one against `npm/open-source-project-boilerplate` to address this issue.
