### ISSUE TITLE
Get citgm passing

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#193]
Address any, net-new, errors with node's `citgm` (ie. "canary in the gold mine") tool which runs the tests of a number of open source projects with node/npm.

**Comment by MylesBorins** [comment]
**Reproducible failures due to 7**

_These are easily reproducible locally and not failing during install_

vinyl, node-report, iconv, torrent-stream, vinyl-fs

**Reproducible failures due to peer deps**

redium, serialport

**Lots of failures due to cb error (not yet reproducible locally)**

csv-parser, debug, esprima, leveldown, level, pino, through2, uuid, fastify

---

I have a fork of CITGM that adds a label to the CB modules so you can run CITGM with only those modules

https://github.com/MylesBorins/citgm/tree/npm-7

```bash
$ npm i -g mylesborins/citgm#npm-7
$ citgm-all --includeTags npm-7 -J
```

**Comment by MylesBorins** [comment]
Made a request with the build team to get us access to the MacOS machines so we can try and reproduce on those hosts

v

**Comment by darcyclarke** [comment]
Thanks to a bunch of code spelunking by @nlf 🎉 this should be resolved.
