### ISSUE TITLE
[Web] Showcase devDeps on package pages

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#38]
- [ ] Include dev dependencies either within the existing "Dependencies" tab and/or give them their own section

**Comment by ruyadorno** [comment]
I see a `devDependencies` section in the **Dependencies** section already, was this already fixed by your style improvements PR in `wubwub` ?

<img width="1007" alt="Screen Shot 2020-01-03 at 3 52 25 PM" src="https://user-images.githubusercontent.com/220900/71748657-3da1fe80-2e41-11ea-95d1-9aaf8190b363.png">

**Comment by darcyclarke** [comment]
Closing this as the responsibility for the website has switched to another team.
