### ISSUE TITLE
BREAKING CHANGE(config): `--npm-version` & `--node-version` should be removed

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#575]
### Summary
The `--npm-version` flag/option is confusing as we also have a top-level command `npm version` which is not configured by this at all. `--npm-version` is used by dependencies like `npm-pick-manifest` & `libnpmpublish` but _not_ by the CLI itself. If not changed, this may cause issues when we go to implement command-specific configuration.

### Exit Criteria
- [ ] remove `--npm-version` from being user-configurable & hard-code its downstream usage
- [ ] remove `--node-version` from being user-configurable
- [ ] investigate backporting warnings in `v8.x`

### References
- https://docs.npmjs.org/cli/v8/using-npm/config#npm-version
- https://docs.npmjs.com/cli/v8/commands/npm-version
- https://github.com/npm/rfcs/pull/566

**Comment by wraithgar** [comment]
`node-version` also

**Comment by ljharb** [comment]
What do those flags even do?

**Comment by wraithgar** [comment]
They are used in `npm-pick-manifest` to sort the packuments so that "working" ones bubble to the top... we are ok losing that imo.
They are used of course in logging engines conflicts and strict-engines checks.  Strict engines being configurable is specifically the solution to the problem of mismatching engines, no need to override it there.

Finally it is used by arborist when installing optional dependencies.  If the engine/npm versions aren't allowed it skips them.

**Comment by ljharb** [comment]
So they're overrides for package.json engines data?
