### ISSUE TITLE
feat(agent): introduce new, consolidated http agent

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#584]
### Summary
Historically `npm` has had 3-4 different http agents; consolidating on a single one allows us to optimize perf in one place & add new capabilities

### Exit Criteria
- [x] create new `@npmcli/agent` library
- [x] remove legacy agents & refactor code paths to use `@npmcli/agent`
- [ ] add new configs for fine-grained timeouts (ex. time-to-first-byte, total transfer time, idel-time etc.) & bubble them up to the CLI
- [ ] document new configs

**Comment by wraithgar** [comment]
This is blocked while we figure out a feature flag approach for things like this.

**Comment by saquibkhan** [comment]
what is the priority, can this wait?

**Comment by nlf** [comment]
not extremely high priority, but it is a significant fix for any of our users that leverage a proxy. the current http agents we use for proxies do not support socket limiting, so it's fairly common for the folks who use them to end up seeing connection reset errors and extremely long response times since we're sending a _lot_ of http requests without concurrency limits

**Comment by saquibkhan** [comment]
ok, do we know high level effort needed to complete this?

**Comment by burka** [comment]
We have lots of issues due to ECONNRESET while using a internal proxy and setting fetch-retries and fetch-factor doesn't help as seems like it doesn't retry on ECONNRESET. I hope this might help und it would be awesome if it would not be far down the road.

**Comment by saquibkhan** [comment]
it has dependency on experimantal flag - https://github.com/npm/statusboard/issues/631

**Comment by lukekarrys** [comment]
This is complete except for the fine grained configs which will be a followup task here.
