### ISSUE TITLE
investigate issues with `npx` between v8 > v9

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#595]
- anecdotally, seems like there's some issues with parsing args that has changed

**Comment by wraithgar** [comment]
Yep https://github.com/npm/cli/pull/5064

https://github.com/npm/cli/issues/5729

If I run `npm env echo \$PATH` what runs is `"env echo Hello '$PATH'"`

**Comment by lukekarrys** [comment]
I was also seeing a difference between 8.19.2 and 9.0.0. I haven't investigated that yet but I will.

**Comment by lukekarrys** [comment]
I investigated and it was my error. I was using `npm bin` and reading the output of the command without checking the exit code, so it was producing unexpected results. 🤦🏼 

I think this issue was created after I found the bug while talking to @darcyclarke. Since the other issue is being tracked in the CLI repo, I'm going to close this one.
